#
#
server:
  port: 8081
  servlet:
    context-path: /wms
#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: wms
    password: kentin

#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/kt/wms/mapper/**/mapping/*Mapper.xml

#  type-aliases-package: com.kt.wms.model

jwt:
  expireTime: 3600000
  tokenSecret: kentin
  issuer: kentin

logging:
  level:
    root: info
#  file:
#    name: wmsLog.log